# Занятие 6. Загрузка данных из CSV и Excel. Первое знакомство с pandas

## Краткая теория по ноутбуку

На этом занятии мы переходим от простых структур Python к работе с настоящими табличными данными.

Главный инструмент занятия — библиотека **pandas**.  
Она позволяет:
- загружать таблицы из CSV и Excel
- хранить данные в структуре **DataFrame**
- быстро просматривать строки и столбцы
- выбирать нужные столбцы для анализа

### Что важно понять

- **CSV** — это текстовый файл, где значения разделены запятыми.
- **Excel-файл** (`.xlsx`) — это табличный файл с листами, форматированием и формулами.
- **`pandas`** — библиотека для анализа данных в Python.
- **`DataFrame`** — таблица в Python, похожая на лист Excel.
- **Строки** — наблюдения или записи.
- **Столбцы** — признаки, поля, характеристики.

### Основные команды занятия

- `import pandas as pd` — подключить библиотеку
- `pd.read_csv("file.csv")` — загрузить CSV
- `pd.read_excel("file.xlsx", sheet_name="...")` — загрузить Excel-лист
- `df.head()` — посмотреть первые строки
- `df.tail()` — посмотреть последние строки
- `df.shape` — узнать размер таблицы
- `df.columns` — получить названия столбцов
- `df["column"]` — выбрать один столбец
- `df[["col1", "col2"]]` — выбрать несколько столбцов

### Цель занятия

Научиться:
1. загружать данные из CSV и Excel,
2. понимать структуру `DataFrame`,
3. просматривать таблицу,
4. выбирать нужные столбцы для дальнейшего анализа.

## Практическая ячейка 1. Импорт `pandas` и загрузка CSV

### Что делаем
Создаём небольшой CSV-файл прямо в ноутбуке и считываем его в `DataFrame`.

### Функции, методы и синтаксис
- `import pandas as pd` — подключение библиотеки
- `from pathlib import Path` — удобная работа с файлами
- `Path(...).write_text(...)` — сохранить текст в файл
- `pd.read_csv("имя_файла.csv")` — загрузить CSV в `DataFrame`

### На что обратить внимание
CSV — это обычный текстовый файл.  
После загрузки `pandas` превращает его в таблицу, с которой можно работать как с Excel-данными.

In [ ]:
import pandas as pd
from pathlib import Path

csv_text = """product_id,product_name,category,calories,protein,fat,carbs,fiber
1,Яблоко,Фрукты,52,0.3,0.2,14,2.4
2,Куриная грудка,Мясо,165,31,3.6,0,0
3,Овсянка,Крупы,389,16.9,6.9,66.3,10.6
4,Творог 5%,Молочные,121,17,5,3,0
5,Лосось,Рыба,208,20,13,0,0
6,Брокколи,Овощи,34,2.8,0.4,7,2.6
7,Миндаль,Орехи,579,21,49,22,12
8,Банан,Фрукты,89,1.1,0.3,23,2.6"""

Path("../data/lesson_06_nutrition_data.csv").write_text(csv_text, encoding="utf-8")

df_csv = pd.read_csv("../data/lesson_06_nutrition_data.csv")
df_csv

   product_id    product_name  category  calories  protein   fat  carbs  fiber
0           1          Яблоко    Фрукты        52      0.3   0.2   14.0    2.4
1           2  Куриная грудка      Мясо       165     31.0   3.6    0.0    0.0
2           3         Овсянка     Крупы       389     16.9   6.9   66.3   10.6
3           4       Творог 5%  Молочные       121     17.0   5.0    3.0    0.0
4           5          Лосось      Рыба       208     20.0  13.0    0.0    0.0
5           6        Брокколи     Овощи        34      2.8   0.4    7.0    2.6
6           7         Миндаль     Орехи       579     21.0  49.0   22.0   12.0
7           8           Банан    Фрукты        89      1.1   0.3   23.0    2.6

## Практическая ячейка 2. Загрузка Excel-файла

### Что делаем
Открываем Excel-файл занятия и считываем лист `data`.

### Функции, методы и синтаксис
- `pd.read_excel("имя_файла.xlsx", sheet_name="data")` — загрузить лист Excel в `DataFrame`
- `sheet_name="data"` — указывает, с какого листа брать данные

### На что обратить внимание
Ноутбук и Excel-файл должны лежать в одной папке.  
В этой работе используется файл **`lesson_06_pandas_intro.xlsx`**.

In [16]:
try:
    import openpyxl

except:
    %pip install openpyxl
    import openpyxl

# TODO:
# 1. Загрузите Excel-файл "lesson_06_pandas_intro.xlsx"
# 2. Прочитайте лист "data" в DataFrame df_excel
# 3. Выведите df_excel
df_csv.to_excel("../data/lesson_06_pandas_nutrition_intro.xlsx", sheet_name="data", index=False, engine="openpyxl")
df_excel = pd.read_excel("../data/lesson_06_pandas_nutrition_intro.xlsx", sheet_name="data")
df_excel

   product_id    product_name  category  calories  protein   fat  carbs  fiber
0           1          Яблоко    Фрукты        52      0.3   0.2   14.0    2.4
1           2  Куриная грудка      Мясо       165     31.0   3.6    0.0    0.0
2           3         Овсянка     Крупы       389     16.9   6.9   66.3   10.6
3           4       Творог 5%  Молочные       121     17.0   5.0    3.0    0.0
4           5          Лосось      Рыба       208     20.0  13.0    0.0    0.0
5           6        Брокколи     Овощи        34      2.8   0.4    7.0    2.6
6           7         Миндаль     Орехи       579     21.0  49.0   22.0   12.0
7           8           Банан    Фрукты        89      1.1   0.3   23.0    2.6

## Практическая ячейка 3. Просмотр структуры таблицы

### Что делаем
Смотрим первые и последние строки, размер таблицы и названия столбцов.

### Функции, методы и синтаксис
- `df.head()` — первые 5 строк
- `df.tail(3)` — последние 3 строки
- `df.shape` — кортеж вида `(строки, столбцы)`
- `list(df.columns)` — список названий столбцов

### На что обратить внимание
Сначала важно понять структуру таблицы, а уже потом переходить к анализу.

In [17]:
# TODO:
# 1. Выведите первые 5 строк таблицы
# 2. Выведите последние 3 строки
# 3. Выведите размер таблицы через .shape
# 4. Выведите список названий столбцов

display(df_excel.head())
display(df_excel.tail(3))
display(df_excel.shape)
list(df_excel.columns)

   product_id    product_name  category  calories  protein   fat  carbs  fiber
0           1          Яблоко    Фрукты        52      0.3   0.2   14.0    2.4
1           2  Куриная грудка      Мясо       165     31.0   3.6    0.0    0.0
2           3         Овсянка     Крупы       389     16.9   6.9   66.3   10.6
3           4       Творог 5%  Молочные       121     17.0   5.0    3.0    0.0
4           5          Лосось      Рыба       208     20.0  13.0    0.0    0.0

   product_id product_name category  calories  protein   fat  carbs  fiber
5           6     Брокколи    Овощи        34      2.8   0.4    7.0    2.6
6           7      Миндаль    Орехи       579     21.0  49.0   22.0   12.0
7           8        Банан   Фрукты        89      1.1   0.3   23.0    2.6

(8, 8)

['product_id',
 'product_name',
 'category',
 'calories',
 'protein',
 'fat',
 'carbs',
 'fiber']

## Практическая ячейка 4. Выбор одного и нескольких столбцов

### Что делаем
Выбираем один столбец отдельно и несколько столбцов как новую таблицу.

### Функции, методы и синтаксис
- `df["quantity"]` — выбор одного столбца
- `df[["client", "product", "revenue"]]` — выбор нескольких столбцов
- `display(...)` — красиво показать результат в ноутбуке

### На что обратить внимание
Один столбец возвращается как серия, а несколько столбцов — как новый `DataFrame`.

In [18]:
# TODO:
# 1. Выберите столбец "quantity" и сохраните в quantity_column
# 2. Выберите столбцы "client", "product", "revenue" и сохраните в selected_columns
# 3. Выведите оба результата

calories_column = df_excel["calories"]
selected_columns = df_excel[["product_name", "protein", "fat", "carbs"]]

print("Один столбец quantity:")
display(calories_column)

print("Несколько столбцов:")
display(selected_columns)

Один столбец quantity:

0     52
1    165
2    389
3    121
4    208
5     34
6    579
7     89
Name: calories, dtype: int64

Несколько столбцов:

     product_name  protein   fat  carbs
0          Яблоко      0.3   0.2   14.0
1  Куриная грудка     31.0   3.6    0.0
2         Овсянка     16.9   6.9   66.3
3       Творог 5%     17.0   5.0    3.0
4          Лосось     20.0  13.0    0.0
5        Брокколи      2.8   0.4    7.0
6         Миндаль     21.0  49.0   22.0
7           Банан      1.1   0.3   23.0

## Практическая ячейка 5. Мини-задача: описываем структуру набора данных

### Что делаем
Получаем ключевую информацию о таблице: число строк, число столбцов, список полей и первые товары.

### Функции, методы и синтаксис
- `df.shape[0]` — количество строк
- `df.shape[1]` — количество столбцов
- `list(df.columns)` — список всех столбцов
- `df["product"].head(3).tolist()` — первые 3 значения столбца как список
- `df["revenue"].sum()` — сумма по столбцу

### На что обратить внимание
Даже простое описание структуры таблицы — это уже первый шаг анализа данных.

In [ ]:
# TODO:
# 1. Найдите количество строк и сохраните в rows_count
# 2. Найдите количество столбцов и сохраните в columns_count
# 3. Получите список столбцов в columns_list
# 4. Получите первые 3 товара в first_three_products
# 5. Посчитайте общую выручку в total_revenue
# 6. Выведите результаты

rows_count = df_excel.shape[0]
columns_count = df_excel.shape[1]
columns_list = list(df_excel.columns)
first_three_products = df_excel["product_name"].head(3).tolist()
total_calories = df_excel["calories"].sum()

print("Количество строк:", rows_count)
print("Количество столбцов:", columns_count)
print("Список столбцов:", columns_list)
print("Первые 3 товара:", first_three_products)
print("Общая калорийность:", total_calories)

Количество строк: 8
Количество столбцов: 8
Список столбцов: ['product_id', 'product_name', 'category', 'calories', 'protein', 'fat', 'carbs', 'fiber']
Первые 3 товара: ['Яблоко', 'Куриная грудка', 'Овсянка']
Общая выручка: 1637

## Ячейка 6. Тест и самопроверка

### Что делаем
Проверяем:
- загрузку CSV
- загрузку Excel
- размер таблицы
- названия столбцов
- выбор столбцов
- расчёт итоговой выручки

### Функции, методы и синтаксис
- `assert условие` — быстрая автоматическая проверка правильности результата

In [24]:
import pandas as pd

# Замените имена файлов на свои (если они отличаются)
test_csv = pd.read_csv("../data/lesson_06_nutrition_data.csv")
test_excel = pd.read_excel(
    "../data/lesson_06_pandas_nutrition_intro.xlsx", sheet_name="data"
)  # если лист называется "data", иначе уберите параметр или укажите верное имя

# Проверка размерности (8 строк × 8 столбцов)
assert test_csv.shape == (8, 8)
assert test_excel.shape == (8, 8)

# Ожидаемый список колонок
expected_columns = [
    "product_id",
    "product_name",
    "category",
    "calories",
    "protein",
    "fat",
    "carbs",
    "fiber",
]
assert list(test_excel.columns) == expected_columns

# Проверка конкретного значения (калорийность первого продукта — Яблоко)
assert test_excel["calories"].iloc[0] == 52

# Проверка подмножества колонок
assert list(test_excel[["product_name", "category"]].columns) == [
    "product_name",
    "category",
]

# Проверка суммы калорий по всем продуктам (сумма = 1637)
assert test_excel["calories"].sum() == 1637

print("Тест пройден. Все проверки выполнены верно.")

Тест пройден. Все проверки выполнены верно.